backend:
  name: github
  repo: heyomar/share.links
  branch: main

# Uncomment the line below to use a local proxy server for development:
# local_backend: true

media_folder: app/assets/uploads
public_folder: /assets/uploads

collections:
  - name: posts
    label: Posts
    label_singular: Post
    folder: content/posts
    create: true
    slug: "{{slug}}"
    fields:
      - { label: Title, name: title, widget: string }
      - { label: Publish Date, name: date, widget: datetime, date_format: "YYYY-MM-DD", time_format: false, picker_utc: true }
      - { label: Excerpt, name: excerpt, widget: text }
      - { label: Tags, name: tags, widget: list, required: false }
      - { label: Body, name: body, widget: markdown }
